In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"sinojouni","key":"91b53f6ccb4397a37002b9b92e2e71b7"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d rounakbanik/the-movies-dataset

Dataset URL: https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset
License(s): CC0-1.0
Downloading the-movies-dataset.zip to /content
 90% 204M/228M [00:00<00:00, 2.14GB/s]
100% 228M/228M [00:00<00:00, 2.13GB/s]

In [ ]:
!unzip the-movies-dataset.zip -d dataset

Archive:  the-movies-dataset.zip
  inflating: dataset/credits.csv
  inflating: dataset/keywords.csv
  inflating: dataset/links.csv
  inflating: dataset/links_small.csv
  inflating: dataset/movies_metadata.csv
  inflating: dataset/ratings.csv
  inflating: dataset/ratings_small.csv

In [ ]:
import pandas as pd


ratings = pd.read_csv("dataset/ratings.csv", dtype={
    "userId": "int32",
    "movieId": "int32",
    "rating": "float32",
    "timestamp": "int32"
})
links = pd.read_csv("dataset/links.csv", dtype={
    "movieId": "int32",
    "imdbId": "Int32",
    "tmdbId": "Int32"
})

metadata = pd.read_csv("dataset/movies_metadata.csv", low_memory=False)

credits = pd.read_csv("dataset/credits.csv")
keywords = pd.read_csv("dataset/keywords.csv")

In [ ]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [ ]:
links.head()

   movieId  imdbId  tmdbId
0        1  114709     862
1        2  113497    8844
2        3  113228   15602
3        4  114885   31357
4        5  113041   11862

In [ ]:
metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [ ]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [ ]:
links["tmdbId"]   = pd.to_numeric(links["tmdbId"], errors="coerce").astype("Int64")
metadata["id"]    = pd.to_numeric(metadata["id"], errors="coerce").astype("Int64")
credits["id"]     = pd.to_numeric(credits["id"], errors="coerce").astype("Int64")
keywords["id"]    = pd.to_numeric(keywords["id"], errors="coerce").astype("Int64")

In [ ]:
links     = links.dropna(subset=["tmdbId"])
metadata  = metadata.dropna(subset=["id"])
credits   = credits.dropna(subset=["id"])
keywords  = keywords.dropna(subset=["id"])

In [ ]:
links["tmdbId"]  = links["tmdbId"].astype(int)
metadata["id"]   = metadata["id"].astype(int)
credits["id"]    = credits["id"].astype(int)
keywords["id"]   = keywords["id"].astype(int)

In [ ]:
full_df = metadata.merge(links, left_on="id", right_on="tmdbId", how="inner")

In [ ]:
full_df = full_df.merge(credits, on="id", how="left")

In [ ]:
full_df = full_df.merge(keywords, on="id", how="left")

In [ ]:
full_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,title,video,vote_average,vote_count,movieId,imdbId,tmdbId,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Toy Story,False,7.7,5415.0,1,114709,862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Jumanji,False,6.9,2413.0,2,113497,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Grumpier Old Men,False,6.5,92.0,3,113228,15602,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Waiting to Exhale,False,6.1,34.0,4,114885,31357,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Father of the Bride Part II,False,5.7,173.0,5,113041,11862,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [ ]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46911 entries, 0 to 46910
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  46911 non-null  object
 1   belongs_to_collection  4602 non-null   object
 2   budget                 46911 non-null  object
 3   genres                 46911 non-null  object
 4   homepage               8049 non-null   object
 5   id                     46911 non-null  int64
 6   imdb_id                46894 non-null  object
 7   original_language      46900 non-null  object
 8   original_title         46911 non-null  object
 9   overview               45916 non-null  object
 10  popularity             46907 non-null  object
 11  poster_path            46512 non-null  object
 12  production_companies   46907 non-null  object
 13  production_countries   46907 non-null  object
 14  release_date           46823 non-null  object
 15  revenue                46907 non-null  float64
 16  runtime                46643 non-null  float64
 17  spoken_languages       46907 non-null  object
 18  status                 46825 non-null  object
 19  tagline                20909 non-null  object
 20  title                  46907 non-null  object
 21  video                  46907 non-null  object
 22  vote_average           46907 non-null  float64
 23  vote_count             46907 non-null  float64
 24  movieId                46911 non-null  int32
 25  imdbId                 46911 non-null  Int32
 26  tmdbId                 46911 non-null  int64
 27  cast                   46910 non-null  object
 28  crew                   46910 non-null  object
 29  keywords               46910 non-null  object
dtypes: Int32(1), float64(4), int32(1), int64(2), object(22)
memory usage: 10.4+ MB

In [ ]:
drop_cols = [
    "adult",
    "belongs_to_collection",
    "budget",
    "revenue",
    "homepage",
    "poster_path",
    "imdb_id",
    "production_companies",
    "production_countries",
    "spoken_languages",
    "status",
    "video",
    "id",
    "movieId",
    "imdbId",
    "tagline",
    "original_title",

]

df = full_df.drop(columns=drop_cols, errors="ignore")

In [ ]:
df["release_year"] = pd.to_datetime(df["release_date"], errors="coerce").dt.year
df = df.drop(columns=["release_date"])

In [ ]:
for col in ["runtime", "popularity", "vote_average", "vote_count"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df = df.dropna(subset=[
    "genres",
    "original_language",
    "overview",
    "popularity",
    "runtime",
    "title",
    "vote_average",
    "vote_count",
    "tmdbId",
    "cast",
    "crew",
    "keywords",
    "release_year",

])

df = df.reset_index(drop=True)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45830 entries, 0 to 45829
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   genres             45830 non-null  object
 1   original_language  45830 non-null  object
 2   overview           45830 non-null  object
 3   popularity         45830 non-null  float64
 4   runtime            45830 non-null  float64
 5   title              45830 non-null  object
 6   vote_average       45830 non-null  float64
 7   vote_count         45830 non-null  float64
 8   tmdbId             45830 non-null  int64
 9   cast               45830 non-null  object
 10  crew               45830 non-null  object
 11  keywords           45830 non-null  object
 12  release_year       45830 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 4.5+ MB
None

In [ ]:
df.head()

,genres,original_language,overview,popularity,runtime,title,vote_average,vote_count,tmdbId,cast,crew,keywords,release_year
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",1995.0
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",en,When siblings Judy and Peter discover an encha...,17.015539,104.0,Jumanji,6.9,2413.0,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",1995.0
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",en,A family wedding reignites the ancient feud be...,11.712900,101.0,Grumpier Old Men,6.5,92.0,15602,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",1995.0
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,"Cheated on, mistreated and stepped on, the wom...",3.859495,127.0,Waiting to Exhale,6.1,34.0,31357,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",1995.0
4,"[{'id': 35, 'name': 'Comedy'}]",en,Just when George Banks has recovered from his ...,8.387519,106.0,Father of the Bride Part II,5.7,173.0,11862,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",1995.0

In [ ]:
import pandas as pd
import numpy as np
import math, ast

def parse_json_list(x, key="name", topn=None):
    if isinstance(x, list):
        values = [d.get(key, d) if isinstance(d, dict) else d for d in x]
        return values[:topn] if topn else values
    try:
        data = ast.literal_eval(x)
        if isinstance(data, list):
            values = [d.get(key, d) if isinstance(d, dict) else d for d in data]
            return values[:topn] if topn else values
    except Exception:
        return []
    return []

In [ ]:
df["genres"]   = df["genres"].apply(lambda x: parse_json_list(x))
df["cast"]     = df["cast"].apply(lambda x: parse_json_list(x, topn=3))
df["keywords"] = df["keywords"].apply(lambda x: parse_json_list(x))

df["director"] = df["crew"].apply(
    lambda x: [d.get("name") for d in ast.literal_eval(x) if isinstance(d, dict) and d.get("job")=="Director"]
    if isinstance(x, str) else
    [d.get("name") for d in x if isinstance(d, dict) and d.get("job")=="Director"]
)

df = df.drop(columns=["crew"])

df["movie_id"] = df["tmdbId"].astype(str)

In [ ]:
df.head()

,genres,original_language,overview,popularity,runtime,title,vote_average,vote_count,tmdbId,cast,keywords,release_year,director,movie_id
0,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862
1,"[Adventure, Fantasy, Family]",en,When siblings Judy and Peter discover an encha...,17.015539,104.0,Jumanji,6.9,2413.0,8844,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[board game, disappearance, based on children'...",1995.0,[Joe Johnston],8844
2,"[Romance, Comedy]",en,A family wedding reignites the ancient feud be...,11.712900,101.0,Grumpier Old Men,6.5,92.0,15602,"[Walter Matthau, Jack Lemmon, Ann-Margret]","[fishing, best friend, duringcreditsstinger, o...",1995.0,[Howard Deutch],15602
3,"[Comedy, Drama, Romance]",en,"Cheated on, mistreated and stepped on, the wom...",3.859495,127.0,Waiting to Exhale,6.1,34.0,31357,"[Whitney Houston, Angela Bassett, Loretta Devine]","[based on novel, interracial relationship, sin...",1995.0,[Forest Whitaker],31357
4,[Comedy],en,Just when George Banks has recovered from his ...,8.387519,106.0,Father of the Bride Part II,5.7,173.0,11862,"[Steve Martin, Diane Keaton, Martin Short]","[baby, midlife crisis, confidence, aging, daug...",1995.0,[Charles Shyer],11862

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45830 entries, 0 to 45829
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   genres             45830 non-null  object
 1   original_language  45830 non-null  object
 2   overview           45830 non-null  object
 3   popularity         45830 non-null  float64
 4   runtime            45830 non-null  float64
 5   title              45830 non-null  object
 6   vote_average       45830 non-null  float64
 7   vote_count         45830 non-null  float64
 8   tmdbId             45830 non-null  int64
 9   cast               45830 non-null  object
 10  keywords           45830 non-null  object
 11  release_year       45830 non-null  float64
 12  director           45830 non-null  object
 13  movie_id           45830 non-null  object
dtypes: float64(5), int64(1), object(8)
memory usage: 4.9+ MB

In [ ]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int32
 1   movieId    int32
 2   rating     float32
 3   timestamp  int32
dtypes: float32(1), int32(3)
memory usage: 397.1 MB

In [ ]:
ratings_links = ratings.merge(links, on="movieId", how="inner")

In [ ]:
dff=df.merge(ratings_links, left_on="tmdbId", right_on="tmdbId", how="inner")

In [ ]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26141706 entries, 0 to 26141705
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   genres             object
 1   original_language  object
 2   overview           object
 3   popularity         float64
 4   runtime            float64
 5   title              object
 6   vote_average       float64
 7   vote_count         float64
 8   tmdbId             int64
 9   cast               object
 10  keywords           object
 11  release_year       float64
 12  director           object
 13  movie_id           object
 14  userId             int32
 15  movieId            int32
 16  rating             float32
 17  timestamp          int32
 18  imdbId             Int32
dtypes: Int32(1), float32(1), float64(5), int32(3), int64(1), object(8)
memory usage: 3.2+ GB

In [ ]:
dff.head()

,genres,original_language,overview,popularity,runtime,title,vote_average,vote_count,tmdbId,cast,keywords,release_year,director,movie_id,userId,movieId,rating,timestamp,imdbId
0,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862,8,1,4.0,1013443596,114709
1,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862,9,1,4.5,1073837180,114709
2,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862,12,1,4.0,943912205,114709
3,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862,20,1,4.0,1368361348,114709
4,"[Animation, Comedy, Family]",en,"Led by Woody, Andy's toys live happily in his ...",21.946943,81.0,Toy Story,7.7,5415.0,862,"[Tom Hanks, Tim Allen, Don Rickles]","[jealousy, toy, boy, friendship, friends, riva...",1995.0,[John Lasseter],862,24,1,4.0,979869938,114709

In [ ]:
drop_cols = [
"movieId",
"timestamp",
"imdbId",

]

df = dff.drop(columns=drop_cols, errors="ignore")

In [ ]:
cols = ["userId"] + [c for c in df.columns if c != "userId"]
df = df[cols]

df = df.sort_values(by=["userId","tmdbId"]).reset_index(drop=True)

In [ ]:
df.head()

,userId,genres,original_language,overview,popularity,runtime,title,vote_average,vote_count,tmdbId,cast,keywords,release_year,director,movie_id,rating
0,1,"[Mystery, Thriller]",en,Suffering short-term memory loss after a head ...,15.450789,113.0,Memento,8.1,4168.0,77,"[Guy Pearce, Carrie-Anne Moss, Joe Pantoliano]","[individual, insulin, tattoo, waitress, amnesi...",2000.0,[Christopher Nolan],77,4.0
1,1,"[Fantasy, Drama, Mystery]",en,"After narrowly escaping a bizarre accident, a ...",18.303148,113.0,Donnie Darko,7.7,3574.0,141,"[Jake Gyllenhaal, Jena Malone, Patrick Swayze]","[parent child relationship, airplane, time tra...",2001.0,[Richard Kelly],141,5.0
2,1,"[Drama, Action, Crime, Thriller]",en,Batman raises the stakes in his war on crime. ...,123.167259,152.0,The Dark Knight,8.3,12269.0,155,"[Christian Bale, Michael Caine, Heath Ledger]","[dc comics, crime fighter, secret identity, sc...",2008.0,[Christopher Nolan],155,4.0
3,1,"[Action, Drama, History, War]",en,"Enraged at the slaughter of Murron, his new br...",20.755149,177.0,Braveheart,7.7,3404.0,197,"[Mel Gibson, Catherine McCormack, Sophie Marceau]","[individual, scotland, in love with enemy, leg...",1995.0,[Mel Gibson],197,1.0
4,1,[Drama],en,"At an elite, old-fashioned boarding school in ...",19.905716,129.0,Dead Poets Society,8.1,2786.0,207,"[Robin Williams, Ethan Hawke, Robert Sean Leon...","[individual, philosophy, poetry, shakespeare, ...",1989.0,[Peter Weir],207,5.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26141706 entries, 0 to 26141705
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   userId             int32
 1   genres             object
 2   original_language  object
 3   overview           object
 4   popularity         float64
 5   runtime            float64
 6   title              object
 7   vote_average       float64
 8   vote_count         float64
 9   tmdbId             int64
 10  cast               object
 11  keywords           object
 12  release_year       float64
 13  director           object
 14  movie_id           object
 15  rating             float32
dtypes: float32(1), float64(5), int32(1), int64(1), object(8)
memory usage: 2.9+ GB

In [ ]:
df["userId"]   = df["userId"].astype(str)

In [ ]:
df.head()

,userId,genres,original_language,overview,popularity,runtime,title,vote_average,vote_count,tmdbId,cast,keywords,release_year,director,movie_id,rating
0,1,"[Mystery, Thriller]",en,Suffering short-term memory loss after a head ...,15.450789,113.0,Memento,8.1,4168.0,77,"[Guy Pearce, Carrie-Anne Moss, Joe Pantoliano]","[individual, insulin, tattoo, waitress, amnesi...",2000.0,[Christopher Nolan],77,4.0
1,1,"[Fantasy, Drama, Mystery]",en,"After narrowly escaping a bizarre accident, a ...",18.303148,113.0,Donnie Darko,7.7,3574.0,141,"[Jake Gyllenhaal, Jena Malone, Patrick Swayze]","[parent child relationship, airplane, time tra...",2001.0,[Richard Kelly],141,5.0
2,1,"[Drama, Action, Crime, Thriller]",en,Batman raises the stakes in his war on crime. ...,123.167259,152.0,The Dark Knight,8.3,12269.0,155,"[Christian Bale, Michael Caine, Heath Ledger]","[dc comics, crime fighter, secret identity, sc...",2008.0,[Christopher Nolan],155,4.0
3,1,"[Action, Drama, History, War]",en,"Enraged at the slaughter of Murron, his new br...",20.755149,177.0,Braveheart,7.7,3404.0,197,"[Mel Gibson, Catherine McCormack, Sophie Marceau]","[individual, scotland, in love with enemy, leg...",1995.0,[Mel Gibson],197,1.0
4,1,[Drama],en,"At an elite, old-fashioned boarding school in ...",19.905716,129.0,Dead Poets Society,8.1,2786.0,207,"[Robin Williams, Ethan Hawke, Robert Sean Leon...","[individual, philosophy, poetry, shakespeare, ...",1989.0,[Peter Weir],207,5.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26141706 entries, 0 to 26141705
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   userId             object
 1   genres             object
 2   original_language  object
 3   overview           object
 4   popularity         float64
 5   runtime            float64
 6   title              object
 7   vote_average       float64
 8   vote_count         float64
 9   tmdbId             int64
 10  cast               object
 11  keywords           object
 12  release_year       float64
 13  director           object
 14  movie_id           object
 15  rating             float32
dtypes: float32(1), float64(5), int64(1), object(9)
memory usage: 3.0+ GB

In [ ]:
#code from chat gpt to get en efficent simple from the dataset so we take the sample based on the nb of users
#here (12k user)
import numpy as np, pandas as pd, math, os

MAX_USERS          = 17_000
MIN_USER_RATINGS   = 10
MIN_ITEM_RATINGS   = 5
VAL_FRACTION       = 0.15
SEED               = 42
np.random.seed(SEED)

interactions = df[["userId", "movie_id", "rating", "tmdbId", "genres", "cast", "keywords", "director", "overview", "original_language", "runtime", "popularity", "vote_average", "vote_count", "release_year", "title"]].copy()

interactions["rating"] = interactions["rating"].astype(float)

user_activity = interactions.groupby("userId").size().rename("n_ratings")
active_users = user_activity[user_activity >= MIN_USER_RATINGS]

quantiles = active_users.quantile([0.5, 0.8, 0.95]).to_dict()

q50 = active_users[active_users <= quantiles[0.5]]
q80 = active_users[(active_users > quantiles[0.5]) & (active_users <= quantiles[0.8])]
q95 = active_users[(active_users > quantiles[0.8]) & (active_users <= quantiles[0.95])]
q99 = active_users[active_users > quantiles[0.95]]

alloc = {
    "q50": int(MAX_USERS * 0.55),
    "q80": int(MAX_USERS * 0.25),
    "q95": int(MAX_USERS * 0.12),
    "q99": int(MAX_USERS * 0.08),
}

def sample_index(series, k):
    if len(series) <= k:
        return series.index.tolist()
    return np.random.choice(series.index, size=k, replace=False).tolist()

selected_users = []
selected_users += sample_index(q50, alloc["q50"])
selected_users += sample_index(q80, alloc["q80"])
selected_users += sample_index(q95, alloc["q95"])
selected_users += sample_index(q99, alloc["q99"])
selected_users = list(dict.fromkeys(selected_users))

if len(selected_users) > MAX_USERS:
    selected_users = selected_users[:MAX_USERS]

sampled = interactions[interactions.userId.isin(selected_users)].copy()

item_activity = sampled.groupby("movie_id").size().rename("item_interactions")
valid_items = item_activity[item_activity >= MIN_ITEM_RATINGS].index
sampled = sampled[sampled.movie_id.isin(valid_items)]

sampled = sampled.sort_values(["userId", "movie_id"]).reset_index(drop=True)

unique_users = sampled.userId.unique()
unique_items = sampled.movie_id.unique()

user2idx = {u: i for i, u in enumerate(unique_users)}
item2idx = {m: i for i, m in enumerate(unique_items)}

sampled["user_idx"] = sampled.userId.map(user2idx).astype("int32")
sampled["item_idx"] = sampled.movie_id.map(item2idx).astype("int32")


train_rows = []
val_rows = []
for uid, grp in sampled.groupby("user_idx", sort=False):
    n = len(grp)
    if n <= 1:
        train_rows.append(grp)
        continue
    val_size = max(1, int(math.floor(n * VAL_FRACTION)))
    val_idx = np.random.choice(grp.index, size=val_size, replace=False)
    val_rows.append(grp.loc[val_idx])
    train_rows.append(grp.drop(val_idx))

train_df = pd.concat(train_rows).sort_index().reset_index(drop=True)
val_df   = pd.concat(val_rows).sort_index().reset_index(drop=True)

print("Sampled users:", len(unique_users))
print("Sampled items:", len(unique_items))
print("Train interactions:", len(train_df))
print("Val interactions:", len(val_df))
print("Overall sparsity: {:.4f}".format(1 - (len(sampled) / (len(unique_users) * len(unique_items)))))


print("Avg train ratings per user:", train_df.groupby("user_idx").size().mean())
print("Avg train ratings per item:", train_df.groupby("item_idx").size().mean())

sampled_df = sampled

sampled.head()

Sampled users: 17000
Sampled items: 12988
Train interactions: 1799243
Val interactions: 308177
Overall sparsity: 0.9905
Avg train ratings per user: 105.83782352941176
Avg train ratings per item: 138.5311826301201

,userId,movie_id,rating,tmdbId,genres,cast,keywords,director,overview,original_language,runtime,popularity,vote_average,vote_count,release_year,title,user_idx,item_idx
0,10007,11971,3.0,11971,"[Drama, Comedy, Romance]","[Kenneth Branagh, Richard Briers, Michael Keaton]","[shakespeare, bachelor, new love, rage and hat...",[Kenneth Branagh],"In this Shakespearean farce, Hero and her groo...",en,111.0,8.627240,7.2,194.0,1993.0,Much Ado About Nothing,0,0
1,10007,1572,4.0,1572,"[Action, Thriller]","[Bruce Willis, Jeremy Irons, Samuel L. Jackson]","[bomb, taxi, riddle, robbery, detective, helic...",[John McTiernan],New York detective John McClane is back and ki...,en,128.0,15.138855,6.9,2094.0,1995.0,Die Hard: With a Vengeance,0,1
2,10007,197,5.0,197,"[Action, Drama, History, War]","[Mel Gibson, Catherine McCormack, Sophie Marceau]","[individual, scotland, in love with enemy, leg...",[Mel Gibson],"Enraged at the slaughter of Murron, his new br...",en,177.0,20.755149,7.7,3404.0,1995.0,Braveheart,0,2
3,10007,268,3.0,268,"[Fantasy, Action]","[Jack Nicholson, Michael Keaton, Kim Basinger]","[double life, dc comics, dual identity, chemic...",[Tim Burton],The Dark Knight of Gotham City begins his war ...,en,126.0,19.106730,7.0,2145.0,1989.0,Batman,0,3
4,10007,274,4.0,274,"[Crime, Drama, Thriller]","[Jodie Foster, Anthony Hopkins, Scott Glenn]","[based on novel, psychopath, horror, suspense,...",[Jonathan Demme],"FBI trainee, Clarice Starling ventures into a ...",en,119.0,4.307222,8.1,4549.0,1991.0,The Silence of the Lambs,0,4

In [ ]:
df = sampled

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2107420 entries, 0 to 2107419
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   userId             object
 1   movie_id           object
 2   rating             float64
 3   tmdbId             int64
 4   genres             object
 5   cast               object
 6   keywords           object
 7   director           object
 8   overview           object
 9   original_language  object
 10  runtime            float64
 11  popularity         float64
 12  vote_average       float64
 13  vote_count         float64
 14  release_year       float64
 15  title              object
 16  user_idx           int32
 17  item_idx           int32
dtypes: float64(6), int32(2), int64(1), object(9)
memory usage: 273.3+ MB

In [ ]:
drop_cols = [
"user_idx",
"item_idx",

]

df = df.drop(columns=drop_cols, errors="ignore")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.to_csv("/content/drive/MyDrive/sampled_df.csv", index=False)

NameError: name 'df' is not defined